### ISSUE TITLE
tempdir cleanup permission error when saving localization files

### ISSUE THREAD

**Issue by barentine** [python-microscopy/pyme-omero#1]
Upload still works fine, but throws an unsightly error on the backend and relies on the OS temp file cleaning rather than immediately deleting it.

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "c:\users\laf62\code\python-microscopy\PYME\recipes\base.py", line 857, in save
    mod.save(self.namespace, context)
  File "c:\users\laf62\code\pyme-omero\pyme_omero\recipe_modules\omero_upload.py", line 85, in save
    self.omero_project, loc_filenames)
  File "C:\Users\laf62\.conda\envs\pyme\lib\tempfile.py", line 809, in __exit__
    self.cleanup()
  File "C:\Users\laf62\.conda\envs\pyme\lib\tempfile.py", line 813, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Users\laf62\.conda\envs\pyme\lib\shutil.py", line 500, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\laf62\.conda\envs\pyme\lib\shutil.py", line 395, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\laf62\.conda\envs\pyme\lib\shutil.py", line 393, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\laf62\\AppData\\Local\\Temp\\tmp9g1ovsxy\\Localizations'
```

Addressed with https://github.com/python-microscopy/python-microscopy/pull/446 or alternatives. Can fix internal to this plugin with a 20 second time.sleep call, but that's a little excessive.

**Comment by barentine** [comment]
fixed with merge of python-microscopy/python-microscopy#446
